function topodata2xyz(toponame,gridname,reduction)
% topodata2xyz(toponame,gridname,reduction)
%
% Reads in a topo data point cloud file generated by 
% http://opentopo.sdsc.edu/ and turns it into the .xyz file that can be
% read by BERT
%
% INPUT:
%
% toponame      Name of the point cloud file (including .txt extension)
% gridname      Name of the output file (including extension)
% reduction     Only use every xxth point to reduce file and grid size
%
% Last modified by plattner-at-alumni.ethz.ch, 12/09/2016

fin=fopen(toponame,'r');
fout=fopen(gridname,'w');

% Skip the first line
strin=fgets(fin);

% Now read
%strin=1;
%pointtype=1; % Means it's on the surface
%counter=1;
strin=fgets(fin);
while ischar(strin)  
    red=sscanf(strin,'%f,%f,%f,%d,%f,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d');
    fprintf(fout,'%f %f %f\n',red(1),red(2),red(3));
    if nargin>2
        for skip=1:(reduction-1)
            strin=fgets(fin);
        end
    end
    counter=counter+1;
    strin=fgets(fin);
end

fclose(fout);
fclose(fin);
